### PR TITLE
added back: preys.ix <- as.character(preys[,1])

### PR DESCRIPTION
**Pull request by fredtal**
at line 268.  Somehow it got deleted in the previous pull request.  Yipes.  Sorry.

### CODE REVIEW

**Comment by Philipp-Neubauer** [comment]
the beauty of this workflow is that it doesn't matter, I could just revert and amend the pull request. OR fix it like this...

**Comment by fredtal** [comment]
I need to learn how to use this system better!!  That picture of Theo is ADORABLE.

**Comment by fredtal** [comment]
I'm sorry that I can't figure this out.  I just ran install_github() to get the new version, and it doesn't have the preys.ix line in it; do I need to do something else?

**Comment by Philipp-Neubauer** [comment]
sorry that was my fault! I clicked the wrong button and closed instead of
merged the pull request. Try again now.

On Tue, Jul 14, 2015 at 6:39 AM, fredtal <notifications@github.com> wrote:

> I'm sorry that I can't figure this out. I just ran install_github() to get
> the new version, and it doesn't have the preys.ix line in it; do I need to
> do something else?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Philipp-Neubauer/fastinR/pull/25#issuecomment-121018245>
> .
>



-- 
Phil

**Pull request merged**
